language: php

sudo: false

matrix:
  include:
    - php: 7.1
      env: PHPCS=1 COVERALLS=1

before_script:
  - composer install --prefer-dist
  - if [[ $COVERALLS = 1 ]]; then composer require --dev satooshi/php-coveralls:dev-master; fi
  - if [[ $COVERALLS = 1 ]]; then mkdir -p build/logs; fi

script:
  - vendor/bin/phpunit
  - if [[ $PHPCS = 1 ]]; then vendor/bin/phpcs -p --extensions=php --standard=PSR2 ./src; fi
  - if [[ $COVERALLS = 1 ]]; then phpunit --coverage-clover build/logs/clover.xml; fi
  - if [[ $COVERALLS = 1 ]]; then vendor/bin/coveralls -c .coveralls.yml -v; fi

notifications:
  email: false

after_script:
  - ./update-gh-page.sh
  - ./generate-api.sh
