language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source --dev
  - vendor/bin/parallel-lint -e php,phpt --exclude vendor .

script:
  - vendor/bin/tester -p php -c tests/php-unix.ini tests/ApiGenTests
  - vendor/bin/phpcs -p src/ApiGen --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml --warning-severity=10
  - vendor/bin/phpcs -p tests/ApiGenTests/ApiGen --standard=vendor/zenify/coding-standard/src/ZenifyCodingStandard/ruleset.xml --warning-severity=10
  - vendor/bin/phpcs -p src/ApiGen --standard=vendor/mikulas/code-sniffs/cs/ruleset.xml --sniffs=cs.Debug.DebugFunctionCall,cs.Formatting.UseInAlphabeticalOrder,cs.Formatting.UseWithoutStartingSeparator
  - vendor/bin/phpcs -p tests/ApiGenTests/ApiGen --standard=vendor/mikulas/code-sniffs/cs/ruleset.xml --sniffs=cs.Debug.DebugFunctionCall,cs.Formatting.UseInAlphabeticalOrder,cs.Formatting.UseWithoutStartingSeparator

after_failure:
  - for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
