language: php

sudo: false

matrix:
    include:
        - php: 7.1
          # add variables to enable coverage, coding standard check and static analysis
          env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"

env:
    global:
        # Token for generate-api.sh, so Travis is able to push to "apigen/Api repository
        # It must be encrypted in https://github.com/ApiGen/api local repository
        # See manual how to set it up: https://github.com/TomasVotruba/tomasvotruba.cz/blob/08f0df06674c6bc9db224a69250b8e95060cdc96/.travis.yml#L6-L15
        secure: "CGBmakC27c6di4COrLgC+J7ODX7u7SPqmf7+4nv0ITaZMKm9J/JE8/ohOGpXdaNvEhytxvbRF+vYA9rDgJSRM9jZh94bh8bH8CtFgIZP4i81vgxkZvUl7+dynjz1G/I5XVsMtg3zKTgAkLY7yX8HXcyXEfGTcSjvMh8HlILMPrI="

before_install:
    # Prevents global install of dev dependecies failing
    - composer global config minimum-stability dev
    - composer global config prefer-stable true

install:
    # install composer dependencies
    - composer install
    # Create composer global installs
    - composer create-project apigen/apigen:dev-master temp/apigen-project
    - composer global require apigen/apigen:dev-master

script:
    # run tests
    - vendor/bin/phpunit $PHPUNIT_FLAGS

    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

    # check coding standard (defined in composer.json "scripts" section)
    - composer check-cs
    # check with phpstan (defined in composer.json "scripts" section)
    - composer phpstan

    # Global install checks
    - temp/apigen-project/bin/apigen generate -h
    - ~/.composer/vendor/bin/apigen generate -h

after_script:
    # upload coverage.xml file to Coveralls.io to analyze it
    - |
        if [[ $PHPUNIT_FLAGS != "" ]]; then
            wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
            php coveralls.phar --verbose
        fi

    # Generate ApiGen's api a push it to https://github.com/apigen/api,
    # available at http://www.apigen.org/api/
    - ./generate-api.sh

# do not send success emails, they don't need any action
notifications:
    email:
        on_success: never
