services:
    _defaults:
        autowire: true

    ApiGen\BetterReflection\:
        resource: '..'

    # cached AST Locator
    Roave\BetterReflection\SourceLocator\Ast\Locator: ~
    Roave\BetterReflection\Reflector\ClassReflector: ~
    Roave\BetterReflection\Reflector\FunctionReflector: ~

    Roave\BetterReflection\SourceLocator\Type\SourceLocator:
        factory: ['@ApiGen\BetterReflection\SourceLocator\SourceLocatorsFactory', 'create']

    # nikic\PHP-Parser
    PhpParser\Parser:
        factory: ['@ApiGen\BetterReflection\Parser\ParserFactory', 'create']
    PhpParser\Lexer: ~
    PhpParser\ParserFactory: ~
