services:
    _defaults:
        autowire: true
        autoconfigure: true

    # main application entrance (cannot be autowired)
    Symfony\Component\Console\Application: ~
    ApiGen\Application\ApiGenApplication: ~

    # 3rd party services (cannot be autowired)
    Symfony\Component\Console\Output\ConsoleOutput: ~
    phpDocumentor\Reflection\DocBlockFactory: ~
    phpDocumentor\Reflection\DocBlock\StandardTagFactory: ~

    FSHL\Highlighter: ~
    FSHL\Output\Html: ~

    Latte\Engine: ~
    Symfony\Component\EventDispatcher\EventDispatcher: ~
    phpDocumentor\Reflection\Types\ContextFactory: ~
    phpDocumentor\Reflection\FqsenResolver: ~

    # PSR-4 autodiscovery
    ApiGen\:
        resource: '../../src'
        exclude: '../../src/{Application/Command,Event,Exception}'
#    ApiGen\Console\:
#        resource: '../../src/Console'
    ApiGen\ModularConfiguration\Option\:
        resource: '../../packages/ModularConfiguration/src/Option'
    ApiGen\Element\:
        resource: '../../packages/Element/src'
    ApiGen\StringRouting\:
        resource: '../../packages/StringRouting/src'
    ApiGen\Annotation\:
        resource: '../../packages/Annotation/src'
    ApiGen\Reflection\:
        resource: '../../packages/Reflection/src'
        exclude: "../../packages/Reflection/src/{Exception,Reflection}"

    # root collectors (move to package builder?)
    ApiGen\ModularConfiguration\CommandDecorator: ~
    ApiGen\ModularConfiguration\ConfigurationResolver: ~
    ApiGen\Reflection\TransformerCollector: ~
    ApiGen\Element\ReflectionCollectorCollector: ~

    # services (might be removed, when reflection container aware)
    ApiGen\Configuration\Configuration: ~
    ApiGen\Reflection\Parser\Parser: ~
    ApiGen\Reflection\ReflectionStorage: ~
    ApiGen\Utils\RelativePathResolver: ~