services:
    _defaults:
        autowire: true

    ApiGen\ModularConfiguration\Parameter\ParameterProvider:
        arguments: ["@kernel"]
        autowire: false
    ApiGen\Application\ApiGenApplication: ~
